name: Python Tests

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: kubsu
          POSTGRES_PASSWORD: kubsu
          POSTGRES_DB: kubsu
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --no-root --with test

    - name: Run tests
      env:
        DATABASE_URL: "postgresql+psycopg://kubsu:kubsu@localhost:5432/kubsu"
      run: |
        pytest -v tests/

    - name: Build Docker image
      run: |
        docker build -t kubsu-app .

    - name: Run container tests
      run: |
        docker run --network host -e DATABASE_URL="postgresql+psycopg://kubsu:kubsu@localhost:5432/kubsu" kubsu-app pytest -v tests/